---
# tasks file for myvhost
# 작업 내용 정리
# 1) 웹 패키지 설치 - httpd, mod_ssl
# 2) 웹 서비스 기동- httpd
# 3) 웹 서버 설정
#   * /etc/httpd/conf.d/vhost.conf (<== vhost.conf.j2를 템플릿을 통해 복사)
#   * notify ~ handler
# 4) 방화벽에 서비스 등록 = http, https


# 1) 웹 패키지 설치 - httpd, mod_ssl
- name: 웹 패키지 설치 - httpd, mod_ssl
  yum:
    name: "{{ pkg_web }}" 
    state: latest
# 동일 폴더 내 vars 폴더에 넣어두면 변수 존재시 알아서 인식

# 2) 웹 서비스 기동- httpd
- name: 웹 서비스 기동 - httpd
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ svc_web }}"
# 3) 웹 서버 설정
#   * /etc/httpd/conf.d/vhost.conf (<== vhost.conf.j2를 템플릿을 통해 복사)
# 가상 호스트 설정 위함
#     - ServerAdmin webmaster@ansible1.example.com
#     - ServerName ansible1.example.com
#     - DocumentRoot /var/www/vhosts/ansible1/
#   * notify ~ handler
# 템플릿으로 상대편에게 전송할 것

- name: 웹 서버 설정 - 가상 호스트 설정
  template:  #copy모드와 유사
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
  notify: restart_httpd
  # 핸들러 정의는 핸들러 폴더에서 하기

- name: 웹 디렉토리 생성 - /var/www/vhosts/{{ ansible_hostname }}}
  file:
    path: "/var/www/vhosts/{{ ansible_hostname }}"
    state: directory

- name: 웹 서버 설정 - /var/www/vhosts/{{ansible_hostname}}/index.html 파일 설정
# j2파일에 ansible_hostname으로 되어있음
  template:
    src: index.html.j2
    dest: "/var/www/vhosts/{{ ansible_hostname }}/index.html "
  
# 4) 방화벽에 서비스 등록 = http, https
- name: 방화벽에 서비스 등록 - http, https
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ fw_svc }}"