#- name: myhaproxy
#  src: geerlingguy.haproxy
  # version: "1.1.2"
#- name: myhaproxy2
#  src: https://github.com/geerlingguy/ansible-role-haproxy/archive/1.1.2.tar.gz
- name: myhaproxy3
  src: https://github.com/geerlingguy.git
