---
- name: 각 데이터 센터 시간 동기화
  hosts: datacenters
  # vars:
  #   timesyn_ntp_servers:
  #   - hostname: time.bora.net
  #     iburst: true
  # 그룹변수 등록해놨기 때문
  roles:
  - role: rhel-system-roles.timesync


  post_tasks:
  - name: 타임존 설정
    timezone:
      name: "{{ host_timezone }}"
    notify: restart_chronyd

  handlers:
  - name: restarted_chronyd
    service:
      name: chronyd
      state: restarted