---
- name: 패키지 설치 - {{ package }}
  yum:
    name: "{{ package }}"
    state: latest

- name: 서비스 기동 - "{{ item }}"
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes

# service부분 여러개 지정하기 위해 작성함.
  with_items: "{{ service }}"
