---
- name: 방화벽 패키지 설치 - "{{ package}}"
  yum:
    name: "{{ package}}"
    state: latest

- name: 방화벽 서비스 기동 - "{{ service }}"
  service: 
    name: "{{ service }}"
    state: started
    enabled: yes

- name: 방화벽 서비스 등록 - "{{ fw_svc}}"
  firewalld:
    service: "{{ item }}" 
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ fw_svc }}"
  #임의의 변수 만들고 본 파일에서 fw_svc를 변수 지정하고 목록으로 만듬