---
- name: /var/www/html/index.html 파일 만들기
  copy:
    content: | 
      Hostname -  " {{ ansible_fqdn }}"
      IP addr -  "{{ ansible_default_ipv4.address}}"
    dest: "{{ indexfile }}" 

# 팩트정보 사용할 것
