---
# making plan
# 1) firewall configuration --disable service http, https
# 2) service configuration --disable service - httpd
# 3) web server configuration - remove the file - /var/www/html/index.html
# 4) packages - remove the package - httpd, mod_ssl

- name: Remove and Stop Web service
  hosts: webservers
  tasks:
  - name: disable service - http,https
  # ande firewalld
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: disabled      
    firewalld:
      service: https
      permanent: yes
      immediate: yes
      state: disabled
      
  - name: -disable service - httpd
  # ande service
    service:
      name: httpd
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: Remove the file - /var/www/html/index.html
  # ande file
    file:
      path: /var/www/html/index.html
      state: absent
  
  - name: remove the package - httpd, mod_ssl
    yum:
      name: 
        - httpd
        - mod_ssl
      state: absent