---
- name: /etc/myhosts 파일 생성하기
  hosts: dev
  tasks:
  - name: 템플릿을 사용한 /etc/myhosts 파일 생성하기
    template:
      src: hosts.j2
      dest: /etc/myhosts
      owner: root
      group: root
      mode: '0644'
