---
- name: 웹 컨텐츠 제공
  hosts: webservers
  tasks: 
  - name: 디렉토리 생성 - /webdev
    file: #ande file
      # chmod 2775 /webdev
      path: /webdev
      state: directory
      group: apache
      mode: '2775'
  - name: 링크 파일 생성 - /webdev => /var/www/html/webdev
    file: # 심볼릭 링크 걸기, ande file
      src: /webdev
      dest: /var/www/html/webdev
      state: link
    # 윗부분까지 하면 아직 웹데몬이 못읽음  
  # - name: SELinux 설정
  #   sefcontext: #ande sefcontext
  #   # semanage fcontext -a -t httpd_sys_content_t  /webdev(/.*)?
  #   # restorecon -r /webdev
  #     target: '/webdev(/.*)?' #?의미: 앞단위가 0번 또는 1의 반복
  #     setype: httpd_sys_content_t
  #     state: present

  - name: SELinux 설정 적용 #ande 마지막예제
    command: restorecon -r /webdev  #-irv

  - name: /webdev/index.html 파일 만들기
    copy:
      content: 'WEBSERVERS\n'
      dest: /webdev/index.html
      owner: apache
      grouo: apache
      # apache가 읽을수 있도록. ansible3에서 ls-ldZ /webdev 확인
  - name: 웹 데몬 재기동
    service:
      name: httpd
      state: restarted
      

