---
# Web Server Configuration
# 1) * Install packages
    # yum -y install httpd mod_ssl
# 2) * Web Server settings
    # scp files/index.html ansible#:/var/www/html/index.html
    # to make index file, we should copy it 
# 3) * Web Service startup
    # systemctl enable --now httpd
# 4) * Firewall registration
    # firewall-cmd --permanent --add-service={http,https}
# 5)* SElinux(?)
# make a plan and start


- name: Install and start Apache httpd
  hosts: webservers
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: Web server settings
      copy:
        src: files/index.html
        dest: /var/www/html/index.html 

    - name: Web service startup
      service:      
        name: httpd  
        state: started
        enabled: yes

    - name: Firewall registration - http
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled    

    - name: Firewall registration - https
      firewalld:
        service: https 
        permanent:



