---
- name: 사용자 추가
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
      # useradd user01
      # passwd user01 
  tasks:
  - name: 다중 사용자 추가 및 암호 설정
    user:
      name: "{{ item.name }}"
      password: "{{ item.pw | password_hash('sha512') }}" # doc없으므로 교재 참조
                              # loop로 받는데 쪼개서 못받으므로 구성요소도 지정가능
                              # 각 리스트 한번에는 item쓰기. 리스트 내부 요소는 item.name item.pw로 작성
    with_items: "{{ newusers }}"   # 리스트 요소 한개씩 돌려서
 # sha512 저거는 암호를 암호화하는것. 평문형태 전송 막기위함