---
# play 1 - web1 (ansible1.example.com)
# 1) 패키지 설치 - http, mod_ssl, firewalld
# 2) 웹 서비스 설정 - /var/www/html/index.html
# 3) 서비스 기동 - httpd, firewalld
# 4) 방화벽 등록 - http, https 

# Play2 - localhost
# 1) 웹 확인 - curl http://web1.example.com


# play 1 - web1 (ansible1.example.com)
- name: 웹 서버 설정과 확인
  hosts: web1
  tasks: 
# 1) 패키지 설치 - http, mod_ssl, firewalld 
 # ande yum 참고
  - name: (1) 패키지 설치 - httpd, mod_ssl,firewalld
    yum:
      name:
        - httpd
        - mod_ssl
        - firewalld
      state: latest
# 2) 웹 서비스 설정 - /var/www/html/index.html
  - name: (2) 웹 서비스 설정 - /var/www/html/index.html
    copy:
      content: |
        <html>
        <h1><center><Web1.example.com></center></h1>
        </html>
      dest: /var/www/html/index.html
# 3) 서비스 기동 - httpd, firewalld #ande service
  - name: "(3) 서비스 기동 - httpd, firewalld"
    service:
      name: "{{ item }}"
      state: started 
      enabled: yes
    loop:
      - httpd 
      - firewalld


# 4) 방화벽 등록 - http, https 
  - name: "(4) 방화벽 등록 - http, https" 
    firewalld:
      port: "{{item}}" 
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp

# Play2 - localhost
- name:  웹 요청
  hosts: localhost
  become: no
  tasks:
# 1) 웹 확인 - curl http://web1.example.com
# ande uri
  - name: "(1) 웹 확인 - curl http://web1.example.com"
    uri: 
      url: http://web1
      return_content: true
      status_code: 200
