---
# 1) 방화벽 서비스 OFF - http(80/tcp), https(443/tcp) => firewalld
# 2) 서비스 OFF - httpd => service
# 3) 서비스 설정 삭제 - /var/www/html/index.html => file
# 4) 패키지 삭제 - httpd, mod_ssl => yum, dnf

- name: 웹 서버 복원
  hosts: web1
  tasks:
    - name: (1) 방화벽 서비스 OFF
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled
    
      firewalld:
        service: https
        permanent: yes
        immediate: yes
        state: disabled

      
    - name: (2) httpd 서비스 OFF
      service:
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: (3) 서비스 설정 삭제
      file:
        path: /var/www/html/index.html
        state: absent

    - name: (4) 패키지 삭제
      yum:
        name: 
            - httpd
            - mod_ssl
        state: absent

 


