---
# tasks file for roles/apache
- name: package Installation
  yum:
    name:
    - httpd
    - mod_ssl
    - firewalld
    state: latest

- name: "web server setting - /var/www/html/index.html ( <- index.html.j2 포멧으로 만들기)"
  template: #dynamic file
    src: index.html.j2
    dest: /var/www/html/index.html

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - firewalld
- name: 방화벽 등록
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - http
    - https
